version: '3'
services:
  asgard:
    image: triskacode/asgard
    restart: unless-stopped
    ports:
      - "5000:3000"
    depends_on:
      - achilles
      - athena
      - selene
      - fenrir
  achilles:
    image: triskacode/achilles
    restart: unless-stopped
    ports:
      - "5001:4000"
      - "10000"
    environment:
      - HTTP_PORT=4000
      - MICROSERVICE_PORT=10000
      - USER_SERVICE_HOST=athena
      - USER_SERVICE_PORT=10001
  athena:
    image: triskacode/athena
    restart: unless-stopped
    ports:
      - "5002:4001"
      - "10001"
    environment:
      - HTTP_PORT=4001
      - MICROSERVICE_PORT=10001
      - AUTH_SERVICE_HOST=achilles
      - AUTH_SERVICE_PORT=10000
      - ACCOUNT_SERVICE_HOST=selene
      - ACCOUNT_SERVICE_PORT=10002
      - LOAN_SERVICE_HOST=fenrir
      - LOAN_SERVICE_PORT=10003
  selene:
    image: triskacode/selene
    restart: unless-stopped
    ports:
      - "5003:4002"
      - "10002"
    environment:
      - HTTP_PORT=4002
      - MICROSERVICE_PORT=10002
      - AUTH_SERVICE_HOST=achilles
      - AUTH_SERVICE_PORT=10000
      - USER_SERVICE_HOST=athena
      - USER_SERVICE_PORT=10001
      - STRIPE_API_SECRET_KEY=${STRIPE_API_SECRET_KEY}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
  fenrir:
    image: triskacode/fenrir
    restart: unless-stopped
    ports:
      - "5004:4003"
      - "10003"
    environment:
      - HTTP_PORT=4003
      - MICROSERVICE_PORT=10003
      - AUTH_SERVICE_HOST=achilles
      - AUTH_SERVICE_PORT=10000
      - ACCOUNT_SERVICE_HOST=selene
      - ACCOUNT_SERVICE_PORT=10002
